version: "3.8"

services:
  database:
    container_name: auth-system-database
    image: "postgres:16-alpine"
    restart: always
    environment:
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: auth-system
    ports:
      - 5432:5432
    volumes:
      - database-data:/var/lib/postgresql/data # store data from postgresql in the volume
      - ./database/init.sql:/docker-entrypoint-initdb.d/init.sql # init database with SQL files from local "database" folder

volumes:
  database-data:
    name: auth-system-database-data
    driver: local
