GET http://localhost:3000/users/me
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOiI5NTg3OTliMy05Y2FkLTQ0MzAtYWExNC0yNWU5YzI3N2M1YTUiLCJ1c2VybmFtZSI6ImpvaG5kb2UiLCJpYXQiOjE3MTE3MTI0NTgsImV4cCI6MTcxMTc5ODg1OH0.dLe_soPaCA353wWzo6rTdQ4pj6PZ-lcWnc8VhpyNu_s